import type { GameModeId, ModeConfig } from './types';

const base: Omit<ModeConfig, 'id' | 'name' | 'tagline' | 'mapId'> = {
  baseSpeed: 175,
  speedPerFood: 1.6,
  maxSpeedBonus: 110,
  turnRate: 4.2,
  startLength: 9,
  foodCount: 4,
  scoreMult: 1,
  comboWindow: 4.5,
  hazards: false,
  hazardIntervalStart: 14,
  hazardIntervalMin: 5,
  boss: false,
  bossFirstScore: 900,
  bossScoreStep: 1400,
  timeLimit: null,
  invulnerable: false,
  scorePerSecond: 0,
};

export const MODES: Record<GameModeId, ModeConfig> = {
  classic: {
    ...base,
    id: 'classic',
    name: 'Classic',
    tagline: 'The old rite. One wyrm, one hunger, no mercy.',
    mapId: 'miregloom-gardens',
    foodCount: 3,
  },
  endless: {
    ...base,
    id: 'endless',
    name: 'Endless',
    tagline: 'The Vale unspools forever. So can you.',
    mapId: 'miregloom-gardens',
    foodCount: 5,
    hazards: true,
    hazardIntervalStart: 18,
    hazardIntervalMin: 7,
    boss: true,
  },
  survival: {
    ...base,
    id: 'survival',
    name: 'Survival',
    tagline: 'The dark presses in. Outlast it.',
    mapId: 'ashen-reach',
    foodCount: 2,
    comboWindow: 5.5,
    hazards: true,
    hazardIntervalStart: 10,
    hazardIntervalMin: 3,
    boss: true,
    bossFirstScore: 700,
    bossScoreStep: 1100,
    scorePerSecond: 2,
  },
  timeattack: {
    ...base,
    id: 'timeattack',
    name: 'Time Attack',
    tagline: 'Two minutes of borrowed light. Spend them well.',
    mapId: 'miregloom-gardens',
    foodCount: 8,
    comboWindow: 5,
    scoreMult: 1.25,
    timeLimit: 120,
  },
  hardcore: {
    ...base,
    id: 'hardcore',
    name: 'Hardcore',
    tagline: 'Faster. Crueler. The Vale remembers the bold.',
    mapId: 'ashen-reach',
    baseSpeed: 235,
    speedPerFood: 2.4,
    maxSpeedBonus: 150,
    turnRate: 4.9,
    foodCount: 3,
    comboWindow: 3.2,
    scoreMult: 2,
    hazards: true,
    hazardIntervalStart: 9,
    hazardIntervalMin: 3.5,
    boss: true,
    bossFirstScore: 1100,
    bossScoreStep: 1600,
  },
  zen: {
    ...base,
    id: 'zen',
    name: 'Zen',
    tagline: 'No death. No clock. Only the drifting glow.',
    mapId: 'lumen-deeps',
    baseSpeed: 150,
    speedPerFood: 0.6,
    maxSpeedBonus: 50,
    foodCount: 6,
    comboWindow: 7,
    invulnerable: true,
  },
};

export const MODE_ORDER: readonly GameModeId[] = [
  'classic',
  'endless',
  'survival',
  'timeattack',
  'hardcore',
  'zen',
];
