import type { GameModeId, ModeConfig } from './types';

/**
 * Tuning note: the first pass was paced far too slowly — food sat seconds
 * apart, so combos expired before they could be chained and the wyrm never
 * grew long enough to threaten itself. These values aim for a decision every
 * couple of seconds, a reachable combo chain, and a body that becomes a real
 * maze inside the first minute.
 */
const base: Omit<ModeConfig, 'id' | 'name' | 'tagline' | 'mapId'> = {
  baseSpeed: 235,
  speedPerFood: 3.5,
  maxSpeedBonus: 150,
  turnRate: 4.6,
  startLength: 9,
  foodCount: 6,
  scoreMult: 1,
  comboWindow: 4.5,
  hazards: false,
  hazardIntervalStart: 14,
  hazardIntervalMin: 5,
  boss: false,
  bossFirstScore: 500,
  bossScoreStep: 900,
  timeLimit: null,
  invulnerable: false,
  scorePerSecond: 0,
};

export const MODES: Record<GameModeId, ModeConfig> = {
  classic: {
    ...base,
    id: 'classic',
    name: 'Classic',
    tagline: 'The old rite. One wyrm, one hunger, no mercy.',
    mapId: 'miregloom-gardens',
    foodCount: 7,
    boss: true,
    bossFirstScore: 600,
  },
  endless: {
    ...base,
    id: 'endless',
    name: 'Endless',
    tagline: 'The Vale unspools forever. So can you.',
    mapId: 'miregloom-gardens',
    foodCount: 6,
    hazards: true,
    hazardIntervalStart: 18,
    hazardIntervalMin: 7,
    boss: true,
  },
  survival: {
    ...base,
    id: 'survival',
    name: 'Survival',
    tagline: 'The dark presses in. Outlast it.',
    mapId: 'ashen-reach',
    foodCount: 4,
    comboWindow: 5.5,
    hazards: true,
    hazardIntervalStart: 10,
    hazardIntervalMin: 3,
    boss: true,
    bossFirstScore: 700,
    bossScoreStep: 1100,
    scorePerSecond: 2,
  },
  timeattack: {
    ...base,
    id: 'timeattack',
    name: 'Time Attack',
    tagline: 'Two minutes of borrowed light. Spend them well.',
    mapId: 'miregloom-gardens',
    foodCount: 9,
    comboWindow: 5,
    scoreMult: 1.25,
    timeLimit: 120,
  },
  hardcore: {
    ...base,
    id: 'hardcore',
    name: 'Hardcore',
    tagline: 'Faster. Crueler. The Vale remembers the bold.',
    mapId: 'ashen-reach',
    baseSpeed: 265,
    speedPerFood: 4.5,
    maxSpeedBonus: 190,
    turnRate: 5.2,
    foodCount: 5,
    comboWindow: 3.2,
    scoreMult: 2,
    hazards: true,
    hazardIntervalStart: 9,
    hazardIntervalMin: 3.5,
    boss: true,
    bossFirstScore: 800,
    bossScoreStep: 1200,
  },
  zen: {
    ...base,
    id: 'zen',
    name: 'Zen',
    tagline: 'No death. No clock. Only the drifting glow.',
    mapId: 'lumen-deeps',
    baseSpeed: 170,
    speedPerFood: 0.8,
    maxSpeedBonus: 60,
    foodCount: 7,
    comboWindow: 7,
    invulnerable: true,
  },
};

export const MODE_ORDER: readonly GameModeId[] = [
  'classic',
  'endless',
  'survival',
  'timeattack',
  'hardcore',
  'zen',
];
